<?php

namespace BaseBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CruiseCruiseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiseCruiseCategoryRepository extends EntityRepository
{
	public function findWithCruises($categoryId) {
		$q = "SELECT cc, c, s, p 
			FROM BaseBundle\Entity\CruiseCruiseCategory cc 
			JOIN cc.cruise c
			LEFT JOIN c.prices p
			JOIN c.ship s
			WHERE cc.id = ?1";
		$query = $this->_em->createQuery($q);
		$query->setParameter(1, $categoryId);
   		return $query->getSingleResult();
	}	
	
}
